package AdventOfCode.DayTwo;

public class IDChecksum {
    public static void main(String[] args) {

        String string = "lnfgdsywjyleogambzuchirkpx\n" +
                "nnfqdskfjyteogambzuchirkpx\n" +
                "lnfqdvvwjyteofambzuchirkpf\n" +
                "lnfqdsvwjyteogvmbzuthirkpn\n" +
                "ltfqdsvwjyoeogambxuchirkpx\n" +
                "lnfqcsvwjytzogacbzuchirkpx\n" +
                "lpfpdsvwjyteogambyuchirkpx\n" +
                "pnfqdsvwjyteogqmbzuchinkpx\n" +
                "lnfqdsvwjytyopambzpchirkpx\n" +
                "lnfqisswjyteogadbzuchirkpx\n" +
                "lnfqdsuwjcteogambzuchirepx\n" +
                "lnfqdovwjnteigambzuchirkpx\n" +
                "lnfbdsvwjxteogambzuchirkax\n" +
                "lnfqdsawjyteogamxzuchiwkpx\n" +
                "lncqdsvwjoteogambzuchirfpx\n" +
                "lnfadsrwjyteogambzuchirktx\n" +
                "lnfqdsvhjyteorazbzuchirkpx\n" +
                "lwfqdsvwjytdogambzuchirkhx\n" +
                "lnfqdhvwjyteogambzuhairkpx\n" +
                "lnfqdsvwjytlogambzgchyrkpx\n" +
                "lnfqdsvwjyteogamnzjwhirkpx\n" +
                "lnfodsvwjyteogahuzuchirkpx\n" +
                "lnfqdsvtjyteogamvzwchirkpx\n" +
                "lnfqdsvwjzueogambzuxhirkpx\n" +
                "lnfqxsvljytxogambzuchirkpx\n" +
                "lnfqdsvwjyteogambpyvhirkpx\n" +
                "lqzqdsvwjnteogambzuchirkpx\n" +
                "lnfqdsvwjyteogumbzichirapx\n" +
                "lnfqdbvwjytedgaubzuchirkpx\n" +
                "lnfqdsvwpyteogabbhuchirkpx\n" +
                "nnfqdsvwryteogambzuchiwkpx\n" +
                "lrfqdsvwjeteogambzuchhrkpx\n" +
                "lnfqdsvwxyteogamtzucyirkpx\n" +
                "lnfsdsvwjyteogambzulhirknx\n" +
                "lnfqdsvwjyreoyambzmchirkpx\n" +
                "ltfqdsvwjytdogkmbzuchirkpx\n" +
                "lnfqwbvcjyteogambzuchirkpx\n" +
                "lnfqdsvwjyteogamrzfchirmpx\n" +
                "lnfqdsvwjqteogambzucwirkpy\n" +
                "lnfqdslwjyfeogambzuchikkpx\n" +
                "lnfqdsvwjybeogambzuchikjpx\n" +
                "lofqysvwjyteogasbzuchirkpx\n" +
                "lnfqusvwjyteogambzucverkpx\n" +
                "lnfqdsvwjyteogaibzuchfrkzx\n" +
                "lnfqdsvwjyleogabbzuchirkcx\n" +
                "lnfqdsvqjyteogambzuchdqkpx\n" +
                "lnfqdsvwjwtewgambzuciirkpx\n" +
                "lnfqisvwjatwogambzuchirkpx\n" +
                "lnfqdgvwjyteogambzuchizkix\n" +
                "lnfqdsxwjyteogambyuehirkpx\n" +
                "lpffdsvwjyteogamrzuchirkpx\n" +
                "lnirdsvwjyteogambzuchirkbx\n" +
                "lnfqdsxdjyteogazbzuchirkpx\n" +
                "lnfgdgvwyyteogambzuchirkpx\n" +
                "lnfqxsvwjyteogambzmcwirkpx\n" +
                "lnxqjsvwjyteogambzuchirkqx\n" +
                "lnrqdsvwjpteogkmbzuchirkpx\n" +
                "lnfqdstwjyteoeahbzuchirkpx\n" +
                "lnfqdsvwtuteogambzuchixkpx\n" +
                "lwfqvsvwjyteogambzughirkpx\n" +
                "lnkqdsvwjyfeogambzuuhirkpx\n" +
                "lvvqdsvwjyteogambzuchirkpn\n" +
                "jndqdsvwjyteogzmbzuchirkpx\n" +
                "enfqdszwjyteogambcuchirkpx\n" +
                "lnfqdsvwiyteogakbauchirkpx\n" +
                "lnfqdsvwjyteogtmbzxcdirkpx\n" +
                "fnfqdswwjyteogawbzuchirkpx\n" +
                "lnfqdsvwjydejqambzuchirkpx\n" +
                "lnqqdsvwjyteogambzucbdrkpx\n" +
                "lnfqdsvwjyteogadbzuchirxcx\n" +
                "lnfqdslwjyyeogambzulhirkpx\n" +
                "lnfqdsvwjytecgambzucgirkpb\n" +
                "lbmqdsvwjyteogamkzuchirkpx\n" +
                "lbfqdsvrjyteogambzuchirapx\n" +
                "lnfqdsmwjyteogambzucfarkpx\n" +
                "lnfqasvwoyteofambzuchirkpx\n" +
                "bnfudsvwjyteogambzucharkpx\n" +
                "lnfrdsvwjytxogambzuchirkpg\n" +
                "lbfqdsvwjyteagambzucdirkpx\n" +
                "lxfqdsvwjytuogambzucjirkpx\n" +
                "lnfqdsvwjcteogamyzuchiikpx\n" +
                "lnfodsvwjyteognmbzuchirapx\n" +
                "ltfqdsvwjytedgaxbzuchirkpx\n" +
                "lnfqdshwjyteogambzucsilkpx\n" +
                "lnfqdsvwpyteohambzuchitkpx\n" +
                "wnzqdsvwjyteogambiuchirkpx\n" +
                "lnfqdsvwayteogambzhchirkpw\n" +
                "ltfqcsvwjrteogambzuchirkpx\n" +
                "lnfqdsvwaytekgamvzuchirkpx\n" +
                "lnfqdsvwjyteogambzokpirkpx\n" +
                "lnfqysbwjyeeogambzuchirkpx\n" +
                "lnsqdsvwjyteogambzuchikkpd\n" +
                "lrfqdsvwjyteogahbzochirkpx\n" +
                "lnfqdsvwjyreoggmbzuchjrkpx\n" +
                "lxfqdsvwjyteogkmbzuchirkpp\n" +
                "enhqdbvwjyteogambzuchirkpx\n" +
                "jnfqdsvwjyteogamczuuhirkpx\n" +
                "lnfqdsvwuyteogadbzuchirkpw\n" +
                "lnfqdsvjjytergambznchirkpx\n" +
                "lnfqdsvwjyteoglmbzuceijkpx\n" +
                "lwfqdsvwjyteogamieuchirkpx\n" +
                "lnfqdsvwjfaeogambzqchirkpx\n" +
                "lfbqdjvwjyteogambzuchirkpx\n" +
                "lnfqdsvwjxteoaambzuchirkpp\n" +
                "lnfqdsvwjyheogjmbzgchirkpx\n" +
                "lnfqdskwjyteonambzuchiikpx\n" +
                "lnfqdwvwjyteogambxuchirkph\n" +
                "pnfqdsvwdyteogambzuchihkpx\n" +
                "lnoqdsvwjyteogaybznchirkpx\n" +
                "lnfqdsvwfyxefgambzuchirkpx\n" +
                "lnfqdsvwjyteotamxzmchirkpx\n" +
                "lnfqdsvwjyteigwmbzuchivkpx\n" +
                "lnfqdsvwjytekgambcuchirkwx\n" +
                "lnfqdsvwjuteogamrzulhirkpx\n" +
                "lnfqdsvwjyteogambzucczrgpx\n" +
                "wnfqzsvwjyteogambduchirkpx\n" +
                "lnfqdsowjyteogambuuthirkpx\n" +
                "lnfqdsvrjyteogcmbzuclirkpx\n" +
                "knfqdsvwgyteogambzuchorkpx\n" +
                "lnaqdsvwjytuogdmbzuchirkpx\n" +
                "lnfrdsvwjyteogambluchigkpx\n" +
                "lnfqqzvwjyteogambzkchirkpx\n" +
                "lnfqdsvwjyteogamuzuchgrkux\n" +
                "lnfqdsvnjyteogxmbznchirkpx\n" +
                "lnfqdsvwjyteolajbzuchdrkpx\n" +
                "lnfqdsvwjypeoiagbzuchirkpx\n" +
                "lnrqdsvwjyteozamuzuchirkpx\n" +
                "lnfqdsvwjytkogaubzucqirkpx\n" +
                "lnkbdsvwjyteogacbzuchirkpx\n" +
                "unfqdsvwjybeogambwuchirkpx\n" +
                "lnfqfsvzjyteogambzuchiikpx\n" +
                "lnfqdsvgjyreogahbzuchirkpx\n" +
                "lnfqdsewjyteogavbeuchirkpx\n" +
                "lnfqdsvwjdteogambbuchidkpx\n" +
                "lnfqdsvwjythogambzcchirkvx\n" +
                "lnfqdscwjyteorambzuchirgpx\n" +
                "cnfqdzvwjyteogambzushirkpx\n" +
                "lnfgdsgwjytedgambzuchirkpx\n" +
                "lnfqdsvwbyteogimbzuchdrkpx\n" +
                "lnfqdsswjyteogambzuohbrkpx\n" +
                "lnfqdsvwjytqogabbzachirkpx\n" +
                "lnfqdsvwjyteogmmbzucqiukpx\n" +
                "lnfxdsrwjyteogambzuchnrkpx\n" +
                "lnfqnqvwjyteogambzuchiwkpx\n" +
                "lffqisvwjyteogambzulhirkpx\n" +
                "lnfqdsxwjydeogambzucfirkpx\n" +
                "lnfqdsvwjyteogambzucjirkrp\n" +
                "lnfqdsnqjyteogambduchirkpx\n" +
                "fnfqdmvwjyteogamlzuchirkpx\n" +
                "lnfqvsvwjyteooamdzuchirkpx\n" +
                "lnfqdsvcyyteogambzuchickpx\n" +
                "onfqdsvwjyqeogambzuchirqpx\n" +
                "znfqdcvwjyteoaambzuchirkpx\n" +
                "lnfqdsvwjzteogambzuchidklx\n" +
                "lnfqjsvwjyteogjmbzuchirkpv\n" +
                "lnfqdsvwjytgorambzuchirppx\n" +
                "lzfqdsvwpfteogambzuchirkpx\n" +
                "lnfidsfwjyteogapbzuchirkpx\n" +
                "lnfodsvwbyteobambzuchirkpx\n" +
                "lnlqdsvwjytefgambzuchfrkpx\n" +
                "lnkqdsvwjyteogambzkchgrkpx\n" +
                "tnfqdsvwjyteoiamhzuchirkpx\n" +
                "lnfqdsvwjyteogamllschirkpx\n" +
                "lnfqdsvwjmthogamizuchirkpx\n" +
                "lnfqdbvwjyteogafbzuchirkpb\n" +
                "lnfxosvwjyteogahbzuchirkpx\n" +
                "lnmqdsvwjyzeogambzuchirkcx\n" +
                "lnfqdevbjytxogambzuchirkpx\n" +
                "lnfqdsvwjyteogamzzudhipkpx\n" +
                "lnfqdszwjyteoqambzuchirkpp\n" +
                "lffqdsvwjyteogamtouchirkpx\n" +
                "lnfqdsvhjytfogambzucharkpx\n" +
                "hnfqdsvwjyteogembzschirkpx\n" +
                "lnfqdsvwjateogambzuchirmpa\n" +
                "lnfqdsvcjyteogambzocairkpx\n" +
                "lnfqdsvwjyteogamwzmchirkpd\n" +
                "lnfqzsvwjyteogdmbzuyhirkpx\n" +
                "lnfqdsvwjytfyglmbzuchirkpx\n" +
                "lnfndsvwjyteogambzuchirktf\n" +
                "gnfqdnvwjytevgambzuchirkpx\n" +
                "lnfqdsvwjyteoganbpuchorkpx\n" +
                "lnfpdsvwnyteogambzucqirkpx\n" +
                "fnfqdstejyteogambzuchirkpx\n" +
                "lnfqlsvwjyteowambzuchirkmx\n" +
                "lnfqdsvwjyteogmmdzuchtrkpx\n" +
                "lnfqdsvwcyteogaqbzuchirkqx\n" +
                "lnfqdsvwjytlogtmbzuchiwkpx\n" +
                "lnfqdsvwoyteogambzuczirkwx\n" +
                "lnfqdsvwjyteogzybzucdirkpx\n" +
                "lnfqdvvwjyteogumbzuchiukpx\n" +
                "lnfqbwvwjyteogambzuchjrkpx\n" +
                "lnfgdsvwjyteogambzvchirkzx\n" +
                "lnfqdsvwjvtjogambzuchiokpx\n" +
                "lnfedsvwjyteogambzuchivkph\n" +
                "lhfqusvwjytaogambzuchirkpx\n" +
                "lnfqdsvwjyteogacbzuihirkpv\n" +
                "lnfwdsvwjyteogambzucokrkpx\n" +
                "lnfqtsvwjpteognmbzuchirkpx\n" +
                "anfqdswwjyteogambzucairkpx\n" +
                "lnfqdsvwjyteorambzuchirlsx\n" +
                "lnfqdsvwjytgogambzychirkpc\n" +
                "lnfqdhvwjyteogambzachirklx\n" +
                "lnfwdsvwjyteogaobquchirkpx\n" +
                "rnfqdsvwjiteogambzuhhirkpx\n" +
                "lnfqdsuwjyemogambzuchirkpx\n" +
                "hnfqdsvwjyteogambzuchprfpx\n" +
                "anfqssvwjyteogambzumhirkpx\n" +
                "lnfkdsvwjyteogafbzqchirkpx\n" +
                "lnfqdsvwjyteogacqzuchirspx\n" +
                "lnfqdskwjyteggambzuchiakpx\n" +
                "lnnqdsvwjyteooambzuchihkpx\n" +
                "lnlqdsvjjyteogambzuchgrkpx\n" +
                "lnfqdsvwjyteogamszochirkex\n" +
                "lnfqbsvwjyteogambzqchirepx\n" +
                "lnfqdsbwjcteogambzhchirkpx\n" +
                "lnfqdwvzjyteogambzechirkpx\n" +
                "ynfadsvwdyteogambzuchirkpx\n" +
                "tnfqdsvwjytuogambzuohirkpx\n" +
                "lnfqdsvwjyteogambzaohivkpx\n" +
                "mnfqisvwjyteogagbzuchirkpx\n" +
                "lnfqbsvwjyueogambzuchirkhx\n" +
                "ynfqdsvwjyteogdmbzuchinkpx\n" +
                "lnfqdwhwjyteogambzuchirqpx\n" +
                "mnfqdsvwjyteogambzfchkrkpx\n" +
                "lnfqdsnwjyteogambzgchiqkpx\n" +
                "lnfqdsvwjytergambzuchiuklx\n" +
                "lnfqdqvjjyteogamtzuchirkpx\n" +
                "lnfqdscwjyteorambzuchzrgpx\n" +
                "enfqdevwjyteogaabzuchirkpx\n" +
                "gnfqdsvbjyteogambzuchirkph\n" +
                "lnfqdxvwjyteogambzubhixkpx\n" +
                "lnfqdsvwjyteogambojchihkpx\n" +
                "lnfqdsvwjytdogambzuzhilkpx\n" +
                "lnfqdsvwjyteogamezuqhirtpx\n" +
                "tnfhdsvwjyteogambzuvhirkpx\n" +
                "lnfzdsvwjnteogahbzuchirkpx\n" +
                "lnfqdsvwjyteogambzfzhirkvx\n" +
                "lnfqqsvwjyteogambzuchirgpo\n" +
                "lufqpsvwjythogambzuchirkpx\n" +
                "lnfqdsvwjyteogzmbzuchimkix\n" +
                "lnwqdspwjyteogambzcchirkpx\n" +
                "lnfqdsowjyteogambzuchigypx\n" +
                "lnfqdnvvjyteogambzucjirkpx\n" +
                "lnfjdsvwryteogambzuchirkcx\n" +
                "lnfqdsvwbyteogambzuchirfpb\n" +
                "lnfqdsvwjyheogambzxchprkpx\n" +
                "lnfqmsvwjytezgambzuchirlpx\n" +
                "lnaqdsvwjyteogamdzuzhirkpx\n" +
                "lnoqdsvwjytebgambfuchirkpx\n" +
                "lnfqdtvwjytvogambzuchirkpv";

        IDChecksumLogic idChecksumLogic = new IDChecksumLogic();
        System.out.println(idChecksumLogic.idsChecksum(string));

    }
}
